name: vest_keren
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  animate_do: ^4.2.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  expansion_tile_group: ^1.2.4
  rounded_expansion_tile: ^0.0.13
  intl: ^0.19.0
  data_table_2: ^2.6.0
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.70.2
  get_cli: ^1.8.1
  socket_io_client: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.0
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  http: ^1.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Informasi Section
    - assets/images/militer.jpg
    - assets/images/militer2.jpeg
    - assets/images/web.png
    - assets/images/mikro.png  
    - assets/images/piezo.png  
    - assets/images/wifi.png  
    - assets/images/api.png  
    # Khusus Logo
    - assets/images/logo/stas-panjang.png
    - assets/images/logo/stas-G.png
    # Apalah
    - assets/images/ngawur.jpg
  