name: vest_keren
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  expansion_tile_group: ^1.2.4
  rounded_expansion_tile: ^0.0.13
  intl: ^0.19.0
  data_table_2: ^2.5.10
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.2
  get_cli: ^1.8.1
  socket_io_client: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.0
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  http: ^1.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Khusus Senjata
    - assets/images/senjata/pistol.png
    - assets/images/senjata/ak47.png
    - assets/images/senjata/shotgun.png
    - assets/images/senjata/glock17.png
    - assets/images/senjata/double_barrel.png
    - assets/images/senjata/m416.png
    # Khusus Logo
    - assets/images/logo/stas-panjang.png
    - assets/images/logo/stas-G.png
    # Khusus Arena
    - assets/images/arena/map_keren.png
    # Khusus Rompi Modern
    - assets/images/vest.png
    # Apalah
    - assets/images/ngawur.jpg
  