name: vest_keren
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2 #dipakai
  get: 4.6.6 #dipakai
  get_storage: ^2.1.1 #dipakai
  flutter: 
    sdk: flutter
  animate_do: ^4.2.0 #dipakai
  google_fonts: ^6.1.0 #dipakai
  material_design_icons_flutter: ^7.0.7296 #dipakai
  rounded_expansion_tile: ^0.0.13 
  intl: ^0.19.0
  data_table_2: ^2.6.0 #dipakai
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.70.2
  socket_io_client: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.0 #dipakai
  flutter_screenutil: ^5.9.3
  http: ^1.3.0 #dipakai

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Informasi Section
    - assets/images/Anggota/
    - assets/images/Information/
    - assets/images/logo/
    - assets/images/
  